version: '3.4'

services:
  otel.poc.web:
    image: otelpocweb
    build:
      context: .
      dockerfile: OTel.POC.Web/Dockerfile
    networks:
      - otel-dotnet-poc
    ports:
      - "5000:80"
      - "5001:443"

  rabbitmq:
    image: rabbitmq:3.8.16-management-alpine
    container_name: otel-rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
    hostname: 'otel-rabbitmq'
    restart: 'always'
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/ot
      - ./rabbitmq/log:/var/log/rabbitmq
    networks:
      - otel-dotnet-poc
  
  
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: otel-kafdrop
    restart: 'always'
    ports: 
      - '9000:9000'
    environment: 
      - 'KAFKA_BROKERCONNECT=kafka:29092'
      - 'JVM_OPTS=-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify'
    depends_on: 
      - kafka
    networks: 
      - otel-dotnet-poc
  
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: otel-zookeeper
    restart: 'always'
    environment: 
      - 'ZOOKEEPER_CLIENT_PORT=2181'
      - 'ZOOKEEPER_TICK_TIME=2000'
    ports: 
      - '2181:2181'
    networks: 
      - otel-dotnet-poc
  
  kafka:
    image: confluentinc/cp-kafka
    container_name: otel-kafka
    restart: 'always'
    depends_on: 
      - 'zookeeper'
    ports: 
      - '9092:9092'
    environment: 
      - 'KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092'
      - 'KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092'
      - 'KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      - 'KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeper:2181'
      - 'KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1'
      - 'KAFKA_BROKER_ID=1'
    networks: 
      - otel-dotnet-poc

  elasticsearch01:
      image: bitnami/elasticsearch:latest
      container_name: otel-elasticsearch01
      environment: 
        - node.name=elasticsearch01
        - cluster.name=otel-es-docker-cluster
        - discovery.seed_host=elasticsearch02
        - cluster.initial_master_nodes=elasticsearch01,elasticsearch02
        - bootsrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits: 
        memlock:
          soft: -1
          hard: -1
      volumes: 
        - otel-es-vol-01:/usr/share/elasticsearch/data
      ports: 
        - 9200:9200
      networks: 
        - otel-dotnet-poc

  elasticsearch02:
    image: bitnami/elasticsearch:latest
    container_name: otel-elasticsearch02
    environment: 
      - node.name=elasticsearch02
      - cluster.name=otel-es-docker-cluster
      - discovery.seed_hosts=elasticsearch01
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02
      - bootsrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - otel-es-vol-02:/usr/share/elasticsearch/data
    networks: 
      - otel-dotnet-poc
  
  kibana:
    image: bitnami/kibana
    container_name: otel-kibana
    depends_on: 
      - elasticsearch01
      - elasticsearch02
    ports: 
      - 5601:5601
    environment: 
      ELASTICSEARCH_URL: http://elasticsearch01:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch01:9200","http://elasticsearch02:9200"]'
    networks: 
      - otel-dotnet-poc

  jeager-all-in-one:
    image: jaegertracing/all-in-one:1.22
    container_name: otel-jeager-all-in-one
    depends_on: 
      - elasticsearch01
      - elasticsearch02
      - kibana
    environment: 
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch01:9200
      - LOG_LEVEL=debug
    restart: 'on-failure'
    ports: 
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '14250:14250'
      - '9411:9411'
    networks: 
      - otel-dotnet-poc  

volumes: 
  otel-es-vol-01:
    driver: local
  otel-es-vol-02:
    driver: local  

networks: 
  otel-dotnet-poc :


